using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Problem2
{
    class Problem2
    {
        /// <summary>
        /// for problem 2, fibonacci sequence
        /// horrible code
        /// </summary>
        /// <param name="x"></param>
        /// <param name="y"></param>
        /// <returns></returns>
        static long sum_fib = 0;
        static long Fib(long x, long y)
        {

            if (y > 4000000)
            {
                //
                return x;
            }
            else
            {
                if (y % 2 == 0)
                {
                    sum_fib += y;
                    Console.WriteLine("Y = " + y + " Sum = " + sum_fib);
                }
                return x + Fib(y, x + y);
            }
        }
        /// <summary>
        /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        /// Find the sum of all the even-valued terms in the sequence which do not exceed four million.
        /// </summary>
        static void Main(string[] args)
        {
            long fib = Fib(0, 1);
            Console.ReadKey();
        }
    }
}
